### ISSUE TITLE
Save\Load

### ISSUE THREAD

**Issue by Buvaluy** [Buvaluy/VirtualMachine#32]
Перед началом компиляции сохронять исходный текстовый код в дефолтный файл рядом с exe.
Описание зачем:
Если писать достаточно большую программу без компиляции, и потом при попытки скомпилирывать будет найден ранее неизвестный критический баг который закроет виртуальную машину, человек писавший код, сможет открыть свой код который привел к ошибке и сам найти критическую ошибку, не теряя время на переписывание кода с нуля

**Comment by BorisovDmytro** [comment]
Вешай на меня

**Comment by BorisovDmytro** [comment]
Done
